version: "3.3"
services:
  geth:
    build: .
    container_name: ethereum
    volumes:
      - ./config:/config
      - ./data:/data
    restart: always
    ports:
      - "7777:8545"
  faucet:
    image: chainflag/eth-faucet:1.0.0
    container_name: ethfaucet
    environment:
      - WEB3_PROVIDER=http://geth:8545
      - KEYSTORE=/app/keystore
    ports:
      - "8080:8080"
    links:
      - geth
    volumes:
      - ./config/keystore:/app/keystore
      - ./config/password.txt:/app/password.txt
    command: -interval 1 -chainname "Hackchain"
    depends_on:
      - geth
    restart: always
  Transmitter:
    image: chainflag/eth-challenge-base
    container_name: transmitter
    ports:
      - "20000:20000"
    env_file:
      - .env
    volumes:
      - ./NukeAuction/contracts/:/home/ctf/contracts
      - ./NukeAuction/NukeAuction.yml:/home/ctf/challenge.yml
  NukeAuction:
    image: chainflag/eth-challenge-base
    container_name: nukeauction
    ports:
      - "20001:20000"
    env_file:
      - .env
    volumes:
      - ./NukeAuction/contracts/:/home/ctf/contracts
      - ./NukeAuction/NukeAuction.yml:/home/ctf/challenge.yml
  onChainLotterySecuredx20000:
    image: chainflag/eth-challenge-base
    container_name: onchainlottery
    ports:
      - "20002:20000"
    env_file:
      - .env
    volumes:
      - ./onChainLotterySecuredx20000/contracts/:/home/ctf/contracts
      - ./onChainLotterySecuredx20000/onChainLotterySecuredx20000.yml:/home/ctf/challenge.yml
  TimeRacers:
    image: chainflag/eth-challenge-base
    ports:
      - "20003:20000"
    container_name: timeracers
    env_file:
      - .env
    volumes:
      - ./TimeRacers/contracts/:/home/ctf/contracts
      - ./TimeRacers/TimeRacers.yml:/home/ctf/challenge.yml
  TransparentCasino:
    image: chainflag/eth-challenge-base
    container_name: transparentcasino
    ports:
      - "20004:20000"
    env_file:
      - .env
    volumes:
      - ./TransparentCasino/contracts/:/home/ctf/contracts
      - ./TransparentCasino/TransparentCasino.yml:/home/ctf/challenge.yml
